// Example sentences for the STARTER_WORDS deck.
// Keyed by the exact Italian `front` string from words.js.
// Value = [english, italian] — the SAME sentence in both languages.
// The target word/phrase is wrapped in **double asterisks** in each language.

export const EXAMPLE_SENTENCES = {
  // Greetings & basics
  "ciao": ["**Hi** Marco, long time no see!", "**Ciao** Marco, quanto tempo!"],
  "buongiorno": ["**Good morning**! Did you sleep well?", "**Buongiorno**! Hai dormito bene?"],
  "buonasera": ["**Good evening**, a table for two.", "**Buonasera**, un tavolo per due."],
  "buonanotte": ["**Good night**, sweet dreams!", "**Buonanotte**, sogni d'oro!"],
  "arrivederci": ["**Goodbye**, see you tomorrow!", "**Arrivederci**, a domani!"],
  "per favore": ["Could you speak more slowly, **please**?", "Può parlare più lentamente, **per favore**?"],
  "grazie": ["**Thanks** for the help!", "**Grazie** dell'aiuto!"],
  "prego": ["Thanks! — **You're welcome**.", "Grazie! — **Prego**."],
  "scusa": ["**Sorry**, I didn't mean it.", "**Scusa**, non volevo."],
  "sì": ["**Yes**, I'd love to come.", "**Sì**, vengo volentieri."],
  "no": ["**No**, I prefer tea.", "**No**, preferisco il tè."],
  "come stai?": ["Hi Anna, **how are you?**", "Ciao Anna, **come stai?**"],
  "sto bene": ["**I'm fine** now, don't worry.", "**Sto bene** adesso, non preoccuparti."],
  "come ti chiami?": ["Nice to meet you, **what's your name?**", "Piacere, **come ti chiami?**"],
  "mi chiamo...": ["**My name is** Luca, nice to meet you.", "**Mi chiamo** Luca, piacere."],
  "piacere": ["**Nice to meet you**, I'm Sara.", "**Piacere**, sono Sara."],

  // Pronouns & question words
  "io": ["**I** always take the train.", "**Io** prendo sempre il treno."],
  "tu": ["What do **you** think?", "**Tu** cosa ne pensi?"],
  "lui": ["**He** works at the bakery.", "**Lui** lavora al panificio."],
  "lei": ["**She** speaks four languages.", "**Lei** parla quattro lingue."],
  "noi": ["**We** are going to the beach.", "**Noi** andiamo al mare."],
  "voi": ["Are **you** coming with us?", "**Voi** venite con noi?"],
  "loro": ["**They** have three children.", "**Loro** hanno tre figli."],
  "che cosa": ["**What** are you doing tonight?", "**Che cosa** fai stasera?"],
  "chi": ["**Who** is at the door?", "**Chi** è alla porta?"],
  "dove": ["**Where** do you work?", "**Dove** lavori?"],
  "quando": ["**When** do you finish work?", "**Quando** finisci di lavorare?"],
  "perché": ["**Why** are you laughing?", "**Perché** ridi?"],
  "come": ["**How** do you say it in Italian?", "**Come** si dice in italiano?"],
  "quanto": ["**How much** sugar do you want?", "**Quanto** zucchero vuoi?"],

  // Numbers
  "uno": ["I only need **one**.", "Me ne serve solo **uno**."],
  "due": ["**Two** coffees, please.", "**Due** caffè, per favore."],
  "tre": ["We stayed **three** days in Florence.", "Siamo stati **tre** giorni a Firenze."],
  "quattro": ["The film starts at **four**.", "Il film comincia alle **quattro**."],
  "cinque": ["There are **five** of us for dinner.", "Siamo in **cinque** a cena."],
  "sei": ["My brother is **six** years old.", "Mio fratello ha **sei** anni."],
  "sette": ["My alarm goes off at **seven**.", "La sveglia suona alle **sette**."],
  "otto": ["I take the **eight** o'clock train.", "Prendo il treno delle **otto**."],
  "nove": ["The pharmacy closes at **nine**.", "La farmacia chiude alle **nove**."],
  "dieci": ["It costs **ten** euros.", "Costa **dieci** euro."],
  "cento": ["This book has **a hundred** pages.", "Questo libro ha **cento** pagine."],
  "mille": ["There were **a thousand** people at the concert.", "C'erano **mille** persone al concerto."],

  // Common verbs (infinitive)
  "essere": ["I want **to be** on time for once.", "Voglio **essere** puntuale per una volta."],
  "avere": ["It's nice **to have** true friends.", "Fa piacere **avere** amici sinceri."],
  "fare": ["What do you want **to do** today?", "Cosa vuoi **fare** oggi?"],
  "andare": ["We can **go** on foot, it's close.", "Possiamo **andare** a piedi, è vicino."],
  "venire": ["Can you **come** to dinner tomorrow?", "Puoi **venire** a cena domani?"],
  "parlare": ["I'd like **to speak** with the manager.", "Vorrei **parlare** con il direttore."],
  "mangiare": ["Let's go **eat** something.", "Andiamo a **mangiare** qualcosa."],
  "bere": ["Do you want something **to drink**?", "Vuoi qualcosa da **bere**?"],
  "dormire": ["I can't **sleep** in this heat.", "Non riesco a **dormire** con questo caldo."],
  "vedere": ["Come **see** my new house!", "Vieni a **vedere** la mia casa nuova!"],
  "sapere": ["I want **to know** the truth.", "Voglio **sapere** la verità."],
  "potere": ["It's great **to be able to** work from home.", "È bello **potere** lavorare da casa."],
  "volere": ["**Wanting** isn't enough.", "Non basta **volere**."],
  "dovere": ["I don't like **having to** decide everything.", "Non mi piace **dovere** decidere tutto."],
  "capire": ["I'm starting **to understand** Italian.", "Comincio a **capire** l'italiano."],
  "parlare italiano": ["I'm learning **to speak Italian**.", "Sto imparando a **parlare italiano**."],
  "studiare": ["Tonight I have **to study** for the exam.", "Stasera devo **studiare** per l'esame."],
  "lavorare": ["I don't like **working** on Sundays.", "Non mi piace **lavorare** la domenica."],
  "vivere": ["I'd love **to live** by the sea.", "Mi piacerebbe **vivere** al mare."],
  "amare": ["It's easy **to love** this city.", "È facile **amare** questa città."],

  // Time
  "oggi": ["**Today** I'm staying home.", "**Oggi** resto a casa."],
  "domani": ["See you **tomorrow** at the station!", "Ci vediamo **domani** alla stazione!"],
  "ieri": ["**Yesterday** it rained all day.", "**Ieri** ha piovuto tutto il giorno."],
  "adesso": ["I can't talk **right now**.", "**Adesso** non posso parlare."],
  "sempre": ["He's **always** late.", "È **sempre** in ritardo."],
  "mai": ["I've **never** been to Sicily.", "Non sono **mai** stato in Sicilia."],
  "spesso": ["We **often** eat out.", "Mangiamo **spesso** fuori."],
  "presto": ["Tomorrow I have to get up **early**.", "Domani devo alzarmi **presto**."],
  "tardi": ["It's **late**, I'm going to bed.", "È **tardi**, vado a letto."],
  "settimana": ["Next **week** I'm on holiday.", "La prossima **settimana** sono in vacanza."],
  "mese": ["I'm moving house next **month**.", "Cambio casa il **mese** prossimo."],
  "anno": ["I've been living here for a **year**.", "Vivo qui da un **anno**."],

  // Family
  "famiglia": ["My **family** comes from Puglia.", "La mia **famiglia** viene dalla Puglia."],
  "madre": ["My **mother** cooks really well.", "Mia **madre** cucina benissimo."],
  "padre": ["My **father** works at the hospital.", "Mio **padre** lavora in ospedale."],
  "fratello": ["My **brother** studies in Bologna.", "Mio **fratello** studia a Bologna."],
  "sorella": ["My **sister** is getting married in June.", "Mia **sorella** si sposa a giugno."],
  "figlio": ["Their **son** is three years old.", "Il loro **figlio** ha tre anni."],
  "figlia": ["Her **daughter** plays the piano.", "Sua **figlia** suona il pianoforte."],
  "amico": ["Paolo is an old **friend** of mine.", "Paolo è un mio vecchio **amico**."],
  "amica": ["My best **friend** lives in Turin.", "La mia migliore **amica** vive a Torino."],

  // Food & drink
  "acqua": ["Could I have some **water**, please?", "Posso avere dell'**acqua**, per favore?"],
  "pane": ["I like **bread** with olive oil.", "Mi piace il **pane** con l'olio."],
  "vino": ["Shall we order a bottle of red **wine**?", "Ordiniamo una bottiglia di **vino** rosso?"],
  "caffè": ["I drink my **coffee** without sugar.", "Bevo il **caffè** senza zucchero."],
  "latte": ["There's no **milk** left in the fridge.", "Non c'è più **latte** in frigo."],
  "formaggio": ["This **cheese** is delicious!", "Questo **formaggio** è buonissimo!"],
  "pasta": ["We made **pasta** for lunch.", "A pranzo abbiamo fatto la **pasta**."],
  "pizza": ["This **pizza** is huge!", "Questa **pizza** è enorme!"],
  "carne": ["I don't eat **meat** anymore.", "Non mangio più **carne**."],
  "pesce": ["The **fish** here is always fresh.", "Qui il **pesce** è sempre fresco."],
  "frutta": ["Do you want some **fruit** after dinner?", "Vuoi della **frutta** dopo cena?"],
  "verdura": ["Eat your **vegetables**!", "Mangia la **verdura**!"],
  "dolce": ["Shall we share a **dessert**?", "Dividiamo un **dolce**?"],
  "colazione": ["I always skip **breakfast**.", "Salto sempre la **colazione**."],
  "pranzo": ["What's for **lunch** today?", "Cosa c'è per **pranzo** oggi?"],
  "cena": ["**Dinner**'s at eight, don't be late.", "La **cena** è alle otto, non fare tardi."],

  // Places
  "casa": ["Welcome to my **home**!", "Benvenuto a **casa** mia!"],
  "città": ["Venice is a magical **city**.", "Venezia è una **città** magica."],
  "strada": ["This **street** is always crowded.", "Questa **strada** è sempre affollata."],
  "scuola": ["The **school** is right behind the church.", "La **scuola** è proprio dietro la chiesa."],
  "lavoro": ["I have too much **work** this week.", "Ho troppo **lavoro** questa settimana."],
  "negozio": ["That **shop** sells beautiful shoes.", "Quel **negozio** vende scarpe bellissime."],
  "stazione": ["The **station** is ten minutes away.", "La **stazione** è a dieci minuti."],
  "aeroporto": ["We got to the **airport** early.", "Siamo arrivati presto all'**aeroporto**."],
  "ristorante": ["I know a good **restaurant** nearby.", "Conosco un buon **ristorante** qui vicino."],
  "mercato": ["On Saturdays I go to the **market**.", "Il sabato vado al **mercato**."],

  // Adjectives
  "grande": ["They have a **big** garden.", "Hanno un giardino **grande**."],
  "piccolo": ["My apartment is very **small**.", "Il mio appartamento è molto **piccolo**."],
  "bello": ["The sunset is **beautiful** tonight.", "Il tramonto è **bello** stasera."],
  "brutto": ["That building is really **ugly**.", "Quel palazzo è davvero **brutto**."],
  "buono": ["This wine is really **good**.", "Questo vino è proprio **buono**."],
  "cattivo": ["He's in a **bad** mood today.", "Oggi è di **cattivo** umore."],
  "nuovo": ["Do you like my **new** phone?", "Ti piace il mio telefono **nuovo**?"],
  "vecchio": ["My grandfather's watch is very **old**.", "L'orologio di mio nonno è molto **vecchio**."],
  "caldo": ["It's really **hot** today.", "Oggi fa molto **caldo**."],
  "freddo": ["Close the window, it's **cold**.", "Chiudi la finestra, fa **freddo**."],
  "facile": ["The exam was **easy**.", "L'esame era **facile**."],
  "difficile": ["This word is **difficult** to pronounce.", "Questa parola è **difficile** da pronunciare."],
  "veloce": ["This train is very **fast**.", "Questo treno è molto **veloce**."],
  "lento": ["The service here is a bit **slow**.", "Qui il servizio è un po' **lento**."],
  "felice": ["I'm **happy** to see you!", "Sono **felice** di vederti!"],
  "triste": ["Why are you so **sad**?", "Perché sei così **triste**?"],

  // Useful phrases
  "non capisco": ["Sorry, **I don't understand** the question.", "Mi dispiace, **non capisco** la domanda."],
  "puoi ripetere?": ["Sorry, **can you repeat?**", "Scusa, **puoi ripetere?**"],
  "quanto costa?": ["Nice jacket, **how much does it cost?**", "Bella quella giacca, **quanto costa?**"],
  "dov'è il bagno?": ["Excuse me, **where is the bathroom?**", "Scusi, **dov'è il bagno?**"],
  "mi piace": ["**I like** this song a lot.", "Questa canzone **mi piace** molto."],
  "non lo so": ["What time does it open? **I don't know**.", "A che ora apre? **Non lo so**."],
  "ho fame": ["**I'm hungry**, let's eat!", "**Ho fame**, mangiamo!"],
  "ho sete": ["**I'm thirsty**, do you have any water?", "**Ho sete**, hai dell'acqua?"],
  "a più tardi": ["I'm off to work, **see you later**!", "Vado al lavoro, **a più tardi**!"],
  "buon appetito": ["Everything's ready, **enjoy your meal**!", "È tutto pronto, **buon appetito**!"],

  // From your own word list
  "a presto": ["Thanks for everything, **see you soon**!", "Grazie di tutto, **a presto**!"],
  "ah": ["**Ah**, now I get it!", "**Ah**, adesso ho capito!"],
  "aiuto": ["**Help**! They stole my bag!", "**Aiuto**! Mi hanno rubato la borsa!"],
  "allegra": ["Your sister is always so **cheerful**.", "Tua sorella è sempre così **allegra**."],
  "allegro": ["He's a **cheerful** guy, always laughing.", "È un ragazzo **allegro**, ride sempre."],
  "allora": ["**So**, what do we do now?", "**Allora**, cosa facciamo adesso?"],
  "anche": ["We invited Marco **too**.", "Abbiamo invitato **anche** Marco."],
  "arabo": ["He learned **Arabic** in Egypt.", "Ha imparato l'**arabo** in Egitto."],
  "arte": ["I love Renaissance **art**.", "Adoro l'**arte** del Rinascimento."],
  "banana": ["I put a **banana** in your backpack.", "Ti ho messo una **banana** nello zaino."],
  "banca": ["First I have to stop by the **bank**.", "Prima devo passare in **banca**."],
  "bene": ["Everything's going **well**, thanks.", "Va tutto **bene**, grazie."],
  "Berlino": ["My cousin lives in **Berlin**.", "Mio cugino vive a **Berlino**."],
  "bibita": ["Would you like a cold **drink**?", "Vuoi una **bibita** fresca?"],
  "biscotto": ["Can I have another **cookie**?", "Posso prendere un altro **biscotto**?"],
  "c'è": ["**There's** a pharmacy on the corner.", "**C'è** una farmacia all'angolo."],
  "camerino": ["Can I try it on in the **fitting room**?", "Posso provarlo nel **camerino**?"],
  "cappotto": ["Put your **coat** on, it's cold outside.", "Mettiti il **cappotto**, fuori fa freddo."],
  "cappuccino": ["A **cappuccino** and a croissant, please.", "Un **cappuccino** e un cornetto, per favore."],
  "carino": ["That hat is really **cute**.", "Quel cappello è proprio **carino**."],
  "caro": ["This restaurant is too **expensive**.", "Questo ristorante è troppo **caro**."],
  "carota": ["I need a **carrot** for the soup.", "Mi serve una **carota** per la zuppa."],
  "cassa": ["You pay at the **register** over there.", "Si paga alla **cassa** laggiù."],
  "come va": ["Hi Luca, **how's it going**?", "Ciao Luca, **come va**?"],
  "con": ["I'm going to the cinema **with** Giulia.", "Vado al cinema **con** Giulia."],
  "conto": ["Could you bring us the **bill**, please?", "Ci porta il **conto**, per favore?"],
  "cornetto": ["For breakfast I always have a **croissant**.", "A colazione prendo sempre un **cornetto**."],
  "dov'è": ["**Where is** the bus stop?", "**Dov'è** la fermata dell'autobus?"],
  "dove sono": ["**Where are** my keys?", "**Dove sono** le mie chiavi?"],
  "e": ["I'd like bread **and** cheese.", "Vorrei pane **e** formaggio."],
  "e tu": ["I'm doing fine, **and you**?", "Io sto bene, **e tu**?"],
  "ecco": ["**Here's** your change.", "**Ecco** il resto."],
  "economico": ["We found a **cheap** hotel downtown.", "Abbiamo trovato un hotel **economico** in centro."],
  "entrata": ["The **entrance** is on the other side.", "L'**entrata** è dall'altra parte."],
  "fagiolo": ["Tonight we're making pasta and **beans**.", "Stasera facciamo pasta e **fagioli**."],
  "fantastico": ["The concert was **fantastic**!", "Il concerto è stato **fantastico**!"],
  "farmacia": ["I'm going to the **pharmacy** to buy aspirin.", "Vado in **farmacia** a comprare l'aspirina."],
  "fragola": ["This **strawberry** is really sweet.", "Questa **fragola** è dolcissima."],
  "francese": ["My teacher is **French**.", "La mia insegnante è **francese**."],
  "gelateria": ["There's a great **ice cream shop** in the square.", "C'è un'ottima **gelateria** in piazza."],
  "gonna": ["That **skirt** looks good on you.", "Quella **gonna** ti sta bene."],
  "guarda": ["**Look**, it's snowing!", "**Guarda**, sta nevicando!"],
  "hai bisogno di": ["Do **you need** a hand?", "**Hai bisogno di** una mano?"],
  "ho": ["**I have** two brothers.", "**Ho** due fratelli."],
  "ho bisogno di": ["**I need** a bigger bag.", "**Ho bisogno di** una borsa più grande."],
  "hotel": ["Our **hotel** is near the beach.", "Il nostro **hotel** è vicino alla spiaggia."],
  "i": ["**The** train tickets are expensive.", "**I** biglietti del treno sono cari."],
  "il": ["**The** bread is still warm.", "**Il** pane è ancora caldo."],
  "impermeabile": ["Take your **raincoat**, it's going to rain.", "Prendi l'**impermeabile**, sta per piovere."],
  "in": ["We live **in** the countryside.", "Viviamo **in** campagna."],
  "inglese": ["Do you speak **English**?", "Parli **inglese**?"],
  "io sono": ["**I am** Sara's brother.", "**Io sono** il fratello di Sara."],
  "italiano": ["My grandfather is **Italian**.", "Mio nonno è **italiano**."],
  "l'": ["**The** water is cold.", "**L'**acqua è fredda."],
  "la": ["**The** pizza is ready.", "**La** pizza è pronta."],
  "le": ["**The** shoes are too small.", "**Le** scarpe sono troppo piccole."],
  "lo": ["**The** sugar is in the cupboard.", "**Lo** zucchero è nell'armadio."],
  "lì": ["Put the bags over **there**.", "Metti le borse **lì**."],
  "ma": ["I'd like to come, **but** I can't.", "Vorrei venire, **ma** non posso."],
  "maglietta": ["I bought a white **t-shirt**.", "Ho comprato una **maglietta** bianca."],
  "male": ["I slept **badly** last night.", "Ho dormito **male** stanotte."],
  "mandarino": ["In winter I eat a **mandarin** every day.", "D'inverno mangio un **mandarino** al giorno."],
  "mela": ["I had an **apple** as a snack.", "Ho mangiato una **mela** a merenda."],
  "Milano": ["The train for **Milan** leaves at six.", "Il treno per **Milano** parte alle sei."],
  "mirtillo": ["**Blueberry** jam is my favorite.", "La marmellata di **mirtilli** è la mia preferita."],
  "moderno": ["They live in a **modern** apartment.", "Vivono in un appartamento **moderno**."],
  "moschea": ["There's a **mosque** near the market.", "C'è una **moschea** vicino al mercato."],
  "non": ["I'm **not** hungry tonight.", "Stasera **non** ho fame."],
  "o": ["Tea **or** coffee?", "Tè **o** caffè?"],
  "ombrello": ["I left my **umbrella** on the train.", "Ho lasciato l'**ombrello** sul treno."],
  "ora": ["The trip takes an **hour**.", "Il viaggio dura un'**ora**."],
  "palazzo": ["I live on the top floor of this **building**.", "Abito all'ultimo piano di questo **palazzo**."],
  "panificio": ["The **bakery** opens at six in the morning.", "Il **panificio** apre alle sei del mattino."],
  "panino": ["I'll grab a **sandwich** for lunch.", "Prendo un **panino** per pranzo."],
  "parli": ["**You speak** Italian really well!", "**Parli** molto bene l'italiano!"],
  "parlo": ["**I speak** a little Spanish.", "**Parlo** un po' di spagnolo."],
  "patata": ["Peel the **potato**, please.", "Sbuccia la **patata**, per favore."],
  "pera": ["This **pear** isn't ripe yet.", "Questa **pera** non è ancora matura."],
  "perfetto": ["Tomorrow at three? **Perfect**!", "Domani alle tre? **Perfetto**!"],
  "poi": ["First we eat, **then** we'll see.", "Prima mangiamo, **poi** vediamo."],
  "polpetta": ["There's one **meatball** left.", "È rimasta una **polpetta**."],
  "pomodoro": ["This salad is missing a **tomato**.", "A questa insalata manca un **pomodoro**."],
  "pompelmo": ["In the morning I drink **grapefruit** juice.", "La mattina bevo succo di **pompelmo**."],
  "posta": ["I have to send this letter at the **post office**.", "Devo spedire questa lettera alla **posta**."],
  "qui": ["Sign **here**, please.", "Firmi **qui**, per favore."],
  "ragazza": ["That **girl** is my cousin.", "Quella **ragazza** è mia cugina."],
  "ragazzo": ["Do you know that **guy**?", "Conosci quel **ragazzo**?"],
  "Roma": ["**Rome** is beautiful in spring.", "**Roma** è bella in primavera."],
  "salve": ["**Hello**, I have a reservation.", "**Salve**, ho una prenotazione."],
  "scarpa": ["I lost a **shoe** on the beach.", "Ho perso una **scarpa** in spiaggia."],
  "scusi": ["**Excuse me**, what time is it?", "**Scusi**, che ore sono?"],
  "sei di": ["**Are you from** Rome?", "**Sei di** Roma?"],
  "seria": ["She's a very **serious** student.", "È una studentessa molto **seria**."],
  "serio": ["It wasn't a joke, I'm **serious**.", "Non era una battuta, sono **serio**."],
  "simpatica": ["Your new colleague is really **nice**.", "La tua nuova collega è molto **simpatica**."],
  "simpatico": ["What a **friendly** guy!", "Che tipo **simpatico**!"],
  "solo": ["I **only** have five euros.", "Ho **solo** cinque euro."],
  "sono": ["**I'm** tired today.", "Oggi **sono** stanco."],
  "sono di": ["**I'm from** Naples.", "**Sono di** Napoli."],
  "spagnolo": ["My flatmate is **Spanish**.", "Il mio coinquilino è **spagnolo**."],
  "sta piovendo": ["Don't go out, **it's raining** hard.", "Non uscire, **sta piovendo** forte."],
  "stivale": ["This **boot** has a hole in it.", "Questo **stivale** ha un buco."],
  "studi": ["What **do you study** at university?", "Cosa **studi** all'università?"],
  "studio": ["**I study** two hours a day.", "**Studio** due ore al giorno."],
  "teatro": ["Tonight we're going to the **theater**.", "Stasera andiamo a **teatro**."],
  "tedesco": ["My boss is **German**.", "Il mio capo è **tedesco**."],
  "timida": ["My daughter is a bit **shy** with strangers.", "Mia figlia è un po' **timida** con gli estranei."],
  "un": ["I'd like **a** coffee, thanks.", "Vorrei **un** caffè, grazie."],
  "una": ["I read **a** magazine a month.", "Leggo **una** rivista al mese."],
  "uscita": ["The **exit** is at the end of the corridor.", "L'**uscita** è in fondo al corridoio."],
  "vero": ["It's **true**, I saw it myself.", "È **vero**, l'ho visto io."],
  "vestiti": ["Put your **clothes** in the suitcase.", "Metti i **vestiti** in valigia."],
  "vorrei": ["**I'd like** a table by the window.", "**Vorrei** un tavolo vicino alla finestra."],
  "wow": ["**Wow**, what a view!", "**Wow**, che vista!"],
  "zaino": ["My **backpack** weighs a ton.", "Il mio **zaino** pesa una tonnellata."],
  "è": ["The coffee **is** already cold.", "Il caffè **è** già freddo."],
  "è di": ["Marco **is from** Milan.", "Marco **è di** Milano."],
};
