// Starter deck of common Italian words/phrases. front = Italian, back = English.
// More can be added from the app's "Add card" panel; these just seed the deck.

export const STARTER_WORDS = [
  // Greetings & basics
  ["ciao", "hi / bye"],
  ["buongiorno", "good morning"],
  ["buonasera", "good evening"],
  ["buonanotte", "good night"],
  ["arrivederci", "goodbye"],
  ["per favore", "please"],
  ["grazie", "thank you"],
  ["prego", "you're welcome"],
  ["scusa", "sorry / excuse me"],
  ["sì", "yes"],
  ["no", "no"],
  ["come stai?", "how are you?"],
  ["sto bene", "I'm well"],
  ["come ti chiami?", "what's your name?"],
  ["mi chiamo...", "my name is..."],
  ["piacere", "nice to meet you"],

  // Pronouns & question words
  ["io", "I"],
  ["tu", "you (informal)"],
  ["lui", "he"],
  ["lei", "she / you (formal)"],
  ["noi", "we"],
  ["voi", "you (plural)"],
  ["loro", "they"],
  ["che cosa", "what"],
  ["chi", "who"],
  ["dove", "where"],
  ["quando", "when"],
  ["perché", "why / because"],
  ["come", "how"],
  ["quanto", "how much"],

  // Numbers
  ["uno", "one"],
  ["due", "two"],
  ["tre", "three"],
  ["quattro", "four"],
  ["cinque", "five"],
  ["sei", "six"],
  ["sette", "seven"],
  ["otto", "eight"],
  ["nove", "nine"],
  ["dieci", "ten"],
  ["cento", "one hundred"],
  ["mille", "one thousand"],

  // Common verbs (infinitive)
  ["essere", "to be"],
  ["avere", "to have"],
  ["fare", "to do / make"],
  ["andare", "to go"],
  ["venire", "to come"],
  ["parlare", "to speak"],
  ["mangiare", "to eat"],
  ["bere", "to drink"],
  ["dormire", "to sleep"],
  ["vedere", "to see"],
  ["sapere", "to know (a fact)"],
  ["potere", "to be able to / can"],
  ["volere", "to want"],
  ["dovere", "to have to / must"],
  ["capire", "to understand"],
  ["parlare italiano", "to speak Italian"],
  ["studiare", "to study"],
  ["lavorare", "to work"],
  ["vivere", "to live"],
  ["amare", "to love"],

  // Time
  ["oggi", "today"],
  ["domani", "tomorrow"],
  ["ieri", "yesterday"],
  ["adesso", "now"],
  ["sempre", "always"],
  ["mai", "never"],
  ["spesso", "often"],
  ["presto", "early / soon"],
  ["tardi", "late"],
  ["settimana", "week"],
  ["mese", "month"],
  ["anno", "year"],

  // Family
  ["famiglia", "family"],
  ["madre", "mother"],
  ["padre", "father"],
  ["fratello", "brother"],
  ["sorella", "sister"],
  ["figlio", "son"],
  ["figlia", "daughter"],
  ["amico", "friend (m)"],
  ["amica", "friend (f)"],

  // Food & drink
  ["acqua", "water"],
  ["pane", "bread"],
  ["vino", "wine"],
  ["caffè", "coffee"],
  ["latte", "milk"],
  ["formaggio", "cheese"],
  ["pasta", "pasta"],
  ["pizza", "pizza"],
  ["carne", "meat"],
  ["pesce", "fish"],
  ["frutta", "fruit"],
  ["verdura", "vegetables"],
  ["dolce", "dessert / sweet"],
  ["colazione", "breakfast"],
  ["pranzo", "lunch"],
  ["cena", "dinner"],

  // Places
  ["casa", "house / home"],
  ["città", "city"],
  ["strada", "street"],
  ["scuola", "school"],
  ["lavoro", "work"],
  ["negozio", "shop"],
  ["stazione", "station"],
  ["aeroporto", "airport"],
  ["ristorante", "restaurant"],
  ["mercato", "market"],

  // Adjectives
  ["grande", "big"],
  ["piccolo", "small"],
  ["bello", "beautiful"],
  ["brutto", "ugly"],
  ["buono", "good"],
  ["cattivo", "bad"],
  ["nuovo", "new"],
  ["vecchio", "old"],
  ["caldo", "hot"],
  ["freddo", "cold"],
  ["facile", "easy"],
  ["difficile", "difficult"],
  ["veloce", "fast"],
  ["lento", "slow"],
  ["felice", "happy"],
  ["triste", "sad"],

  // Useful phrases
  ["non capisco", "I don't understand"],
  ["puoi ripetere?", "can you repeat?"],
  ["quanto costa?", "how much does it cost?"],
  ["dov'è il bagno?", "where is the bathroom?"],
  ["mi piace", "I like it"],
  ["non lo so", "I don't know"],
  ["ho fame", "I'm hungry"],
  ["ho sete", "I'm thirsty"],
  ["a più tardi", "see you later"],
  ["buon appetito", "enjoy your meal"],
];

// Larger reserve pool, not loaded by default. The app pulls from this
// automatically to top up your deck as words graduate into infrequent
// rotation, so you always have fresh material without curating it yourself.
export const RESERVE_WORDS = [
  // Days & months
  ["lunedì", "Monday"],
  ["martedì", "Tuesday"],
  ["mercoledì", "Wednesday"],
  ["giovedì", "Thursday"],
  ["venerdì", "Friday"],
  ["sabato", "Saturday"],
  ["domenica", "Sunday"],
  ["gennaio", "January"],
  ["febbraio", "February"],
  ["marzo", "March"],
  ["aprile", "April"],
  ["maggio", "May"],
  ["giugno", "June"],
  ["luglio", "July"],
  ["agosto", "August"],
  ["settembre", "September"],
  ["ottobre", "October"],
  ["novembre", "November"],
  ["dicembre", "December"],

  // More numbers
  ["undici", "eleven"],
  ["dodici", "twelve"],
  ["tredici", "thirteen"],
  ["quattordici", "fourteen"],
  ["quindici", "fifteen"],
  ["venti", "twenty"],
  ["trenta", "thirty"],
  ["quaranta", "forty"],
  ["cinquanta", "fifty"],

  // Colors
  ["rosso", "red"],
  ["blu", "blue"],
  ["verde", "green"],
  ["giallo", "yellow"],
  ["nero", "black"],
  ["bianco", "white"],
  ["grigio", "gray"],
  ["arancione", "orange"],
  ["viola", "purple"],
  ["rosa", "pink"],
  ["marrone", "brown"],

  // Body
  ["testa", "head"],
  ["mano", "hand"],
  ["braccio", "arm"],
  ["gamba", "leg"],
  ["piede", "foot"],
  ["occhio", "eye"],
  ["orecchio", "ear"],
  ["naso", "nose"],
  ["bocca", "mouth"],
  ["capelli", "hair"],
  ["cuore", "heart"],
  ["schiena", "back (body)"],
  ["dito", "finger"],

  // Animals
  ["cane", "dog"],
  ["gatto", "cat"],
  ["cavallo", "horse"],
  ["uccello", "bird"],
  ["mucca", "cow"],
  ["maiale", "pig"],
  ["pecora", "sheep"],
  ["topo", "mouse"],
  ["leone", "lion"],
  ["orso", "bear"],
  ["elefante", "elephant"],
  ["coniglio", "rabbit"],

  // Clothing
  ["vestito", "dress"],
  ["camicia", "shirt"],
  ["pantaloni", "pants"],
  ["scarpe", "shoes"],
  ["giacca", "jacket"],
  ["cappello", "hat"],
  ["maglione", "sweater"],
  ["calzini", "socks"],
  ["cintura", "belt"],
  ["guanti", "gloves"],

  // Weather
  ["clima", "climate"],
  ["pioggia", "rain"],
  ["sole", "sun"],
  ["neve", "snow"],
  ["vento", "wind"],
  ["nuvola", "cloud"],
  ["temporale", "thunderstorm"],
  ["nebbia", "fog"],
  ["arcobaleno", "rainbow"],

  // Transportation
  ["macchina", "car"],
  ["treno", "train"],
  ["autobus", "bus"],
  ["bicicletta", "bicycle"],
  ["aereo", "airplane"],
  ["nave", "ship"],
  ["taxi", "taxi"],
  ["metro", "subway"],

  // Professions
  ["medico", "doctor"],
  ["insegnante", "teacher"],
  ["avvocato", "lawyer"],
  ["ingegnere", "engineer"],
  ["cuoco", "cook"],
  ["artista", "artist"],
  ["infermiere", "nurse"],
  ["poliziotto", "police officer"],
  ["scrittore", "writer"],
  ["musicista", "musician"],

  // Emotions & traits
  ["arrabbiato", "angry"],
  ["stanco", "tired"],
  ["annoiato", "bored"],
  ["sorpreso", "surprised"],
  ["spaventato", "scared"],
  ["geloso", "jealous"],
  ["orgoglioso", "proud"],
  ["curioso", "curious"],
  ["timido", "shy"],
  ["coraggioso", "brave"],

  // More verbs
  ["comprare", "to buy"],
  ["vendere", "to sell"],
  ["aprire", "to open"],
  ["chiudere", "to close"],
  ["iniziare", "to start"],
  ["finire", "to finish"],
  ["giocare", "to play"],
  ["correre", "to run"],
  ["camminare", "to walk"],
  ["guardare", "to watch / look"],
  ["ascoltare", "to listen"],
  ["scrivere", "to write"],
  ["leggere", "to read"],
  ["pensare", "to think"],
  ["credere", "to believe"],
  ["trovare", "to find"],
  ["perdere", "to lose"],
  ["portare", "to bring / carry"],
  ["mettere", "to put"],
  ["prendere", "to take"],
  ["dare", "to give"],
  ["ricevere", "to receive"],
  ["chiedere", "to ask"],
  ["rispondere", "to answer"],
  ["aiutare", "to help"],
  ["cercare", "to look for"],
  ["aspettare", "to wait"],
  ["tornare", "to return"],
  ["uscire", "to go out"],
  ["entrare", "to enter"],

  // Everyday objects
  ["libro", "book"],
  ["penna", "pen"],
  ["matita", "pencil"],
  ["quaderno", "notebook"],
  ["telefono", "phone"],
  ["computer", "computer"],
  ["chiave", "key"],
  ["borsa", "bag"],
  ["orologio", "watch / clock"],
  ["finestra", "window"],
  ["porta", "door"],
  ["tavolo", "table"],
  ["sedia", "chair"],
  ["letto", "bed"],
  ["specchio", "mirror"],
  ["lampada", "lamp"],
  ["giornale", "newspaper"],
  ["lettera", "letter"],
  ["regalo", "gift"],
  ["festa", "party"],
  ["musica", "music"],
  ["gioco", "game"],

  // Prepositions & adverbs
  ["sopra", "above"],
  ["sotto", "below"],
  ["dentro", "inside"],
  ["fuori", "outside"],
  ["vicino", "near"],
  ["lontano", "far"],
  ["davanti", "in front"],
  ["dietro", "behind"],
  ["insieme", "together"],
  ["ancora", "still / again"],
  ["già", "already"],
  ["forse", "maybe"],
  ["molto", "very / a lot"],
  ["poco", "a little"],
  ["troppo", "too much"],
  ["subito", "right away"],

  // House
  ["cucina", "kitchen"],
  ["bagno", "bathroom"],
  ["camera", "bedroom"],
  ["salotto", "living room"],
  ["giardino", "garden"],
  ["tetto", "roof"],
  ["muro", "wall"],
  ["pavimento", "floor"],
  ["scala", "stairs"],

  // More food
  ["uovo", "egg"],
  ["zucchero", "sugar"],
  ["sale", "salt"],
  ["olio", "oil"],
  ["riso", "rice"],
  ["pollo", "chicken"],
  ["torta", "cake"],
  ["gelato", "ice cream"],
  ["succo", "juice"],
  ["tè", "tea"],
  ["burro", "butter"],
  ["marmellata", "jam"],

  // More places
  ["ospedale", "hospital"],
  ["chiesa", "church"],
  ["biblioteca", "library"],
  ["museo", "museum"],
  ["parco", "park"],
  ["spiaggia", "beach"],
  ["montagna", "mountain"],
  ["fiume", "river"],
  ["lago", "lake"],
  ["mare", "sea"],
  ["isola", "island"],
  ["ponte", "bridge"],
  ["piazza", "square (plaza)"],

  // Phrases
  ["buon compleanno", "happy birthday"],
  ["in bocca al lupo", "good luck"],
  ["che ore sono?", "what time is it?"],
  ["mi dispiace", "I'm sorry"],
  ["non c'è problema", "no problem"],
  ["va bene", "okay / fine"],
  ["che peccato", "what a shame"],
  ["auguri", "best wishes"],
  ["salute", "cheers / bless you"],
  ["certo", "of course"],
];
